deploy: validate cpuset
Signed-off-by: Wu Zhangjin <wuzhangjin@gmail.com>

diff --git a/tools/deploy/run b/tools/deploy/run
--- a/tools/deploy/run
+++ b/tools/deploy/run
@@ -19,6 +19,12 @@ TOP_DIR=$(cd $(dirname $0)/../../ && pwd)
 [ -z "$lab_name" ] && lab_name=$CURRENT
 [ -n "$lab_alive" ] && lab_life=$lab_alive
 
+if [ -n "$lab_cpuset" ]; then
+  total=`grep processor /proc/cpuinfo | wc -l`
+  echo "$lab_cpuset" | egrep -v "`seq $total 100` | tr ' ' '|'" > /dev/null
+  [ $? -ne 0 ] && echo "LOG: cpuset invalid" && exit 1
+fi
+
 [ ! -d $LAB_OUTPUT ] && mkdir -p $LAB_OUTPUT
 VNC_IDENTIFY=1; [ $lab_identify -eq 0 ] && VNC_IDENTIFY=0
 
