docker: fix up random network create
use random network if no VNC_NET specified and limit the retry max times.

Signed-off-by: Wu Zhangjin <falcon@ruma.tech>

diff --git a/tools/docker/config b/tools/docker/config
--- a/tools/docker/config
+++ b/tools/docker/config
@@ -980,28 +980,39 @@ create_cloud_lab_net ()
   if [ $? -ne 0 ]; then
     [ -z "$VNC_NET_MASK" ] && VNC_NET_MASK=16
 
-    while :; do
+    net_retry_count=0
+    NET_RETRY_MAX=10
+    while [ $net_retry_count -lt $NET_RETRY_MAX ]; do
       if [ -z "$VNC_NET" ]; then
+        # Init one for the first try
         VNC_NET=172.20.19.0/$VNC_NET_MASK
       else
+        # If old not work, use a random one
         VNC_NET=`get_random_net`/$VNC_NET_MASK
       fi
       VNC_NET_PREFIX=$(echo $VNC_NET | cut -d'/' -f1 | cut -d '.' -f1-$((5-$VNC_NET_MASK/8)))
-      VNC_GATEWAY=$VNC_NET_PREFIX.1
+      VNC_GATEWAY=${VNC_NET_PREFIX}.1
 
-      docker network create --driver bridge --subnet=$VNC_NET --gateway=$VNC_GATEWAY $VNC_NET_NAME 2>/dev/null
-      [ $? -eq 0 ] && break
+      docker network create --driver bridge --subnet=$VNC_NET --gateway=$VNC_GATEWAY $VNC_NET_NAME
+      if [ $? -eq 0 ]; then
+        echo "LOG: Created network with driver: bridge, subnet: $VNC_NET, gateway: $VNC_GATEWAY" >&2
+        break
+      else
+        echo "WARN: Failed to create network with driver: bridge, subnet: $VNC_NET, gateway: $VNC_GATEWAY, retry: $net_retry_count/$NET_RETRY_MAX" >&2
+        net_retry_count=`expr $net_retry_count + 1`
+        sleep 1
+      fi
     done
   else
     VNC_NET=`docker inspect --format "{{ .IPAM.Config }}" $VNC_NET_NAME | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b/[0-9]{1,2}"`
     VNC_NET_MASK=`echo $VNC_NET | cut -d'/' -f2`
     VNC_NET_PREFIX=$(echo $VNC_NET | cut -d'/' -f1 | cut -d '.' -f1-$((5-$VNC_NET_MASK/8)))
-    VNC_GATEWAY=$VNC_NET_PREFIX.1
+    VNC_GATEWAY=${VNC_NET_PREFIX}.1
   fi
 
   # Set gateway, wproxy and tproxy
-  [ -z "$WPROXY_IP" ] && WPROXY_IP=$VNC_NET_PREFIX.2
-  [ -z "$TPROXY_IP" ] && TPROXY_IP=$VNC_NET_PREFIX.3
+  [ -z "$WPROXY_IP" ] && WPROXY_IP=${VNC_NET_PREFIX}.2
+  [ -z "$TPROXY_IP" ] && TPROXY_IP=${VNC_NET_PREFIX}.3
 
   ## If saved ip is not in the new net ip range of docker, remove it for new generation
   get_var VNC_IP
