tools: increase responsibility for windows
Signed-off-by: Wu Zhangjin <falcon@tinylab.org>

diff --git a/tools/docker/install b/tools/docker/install
--- a/tools/docker/install
+++ b/tools/docker/install
@@ -24,10 +24,10 @@ which docker > /dev/null 2>&1 && exit 0
 
 [ -f /etc/issue ] && grep -qi ubuntu /etc/issue
 if [ $? -eq 0 ]; then
-    echo "LOG: Install docker-ce with $0"
+    echo "INFO: Install docker-ce with $0"
 else
     echo
-    echo "Warning: Docker is missing, but it is required by Linux Lab, please prepare one:"
+    echo "WARN: Docker is missing, but it is required by Linux Lab, please prepare one:"
     echo
     echo "1. Get a preinstalled Linux Lab Disk from https://shop155917374.taobao.com/"
     echo
@@ -80,4 +80,4 @@ $SUDO service docker restart
 
 # FIXME: 'newgrp' not work in script, perhaps should use 'sg' instead
 # see: https://unix.stackexchange.com/questions/18796/how-to-apply-changes-of-newly-added-user-groups-without-needing-to-reboot
-echo "LOG: Without reboot, please issue 'newgrp docker' to work in docker group" >&2
+echo "INFO: Without reboot, please issue 'newgrp docker' to work in docker group" >&2
diff --git a/tools/docker/ssh b/tools/docker/ssh
--- a/tools/docker/ssh
+++ b/tools/docker/ssh
@@ -5,24 +5,43 @@
 # Copyright (C) 2016-2021 Wu Zhangjin <falcon@ruma.tech>
 #
 
+# FIXME: This doesn't work on Windows currently.
+
 TOP_DIR="$(cd "$(dirname "$0")"/../../ && pwd)"
 . "$TOP_DIR"/tools/docker/config >/dev/null
 
+log_print "Check status of $CONTAINER_NAME"
+lab_id=$(docker ps -f name=$CONTAINER_NAME -f status=running -q)
+[ -z "$lab_id" ] && err_print "$LAB_NAME is not running." && exit 1
+log_end
+
+log_print "Get cached data"
 get_vars UNIX_PWD UNIX_USER VNC_IP
+log_end
 
 which sshpass >/dev/null 2>&1
 [ $? -eq 0 ] && SSH_PASS="sshpass -p '$UNIX_PWD'"
 
-SSH_CMD="$SSH_PASS ssh -X -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -t ${UNIX_USER}@${VNC_IP} -p ${CONTAINER_SSH_PORT} 'cd $LAB_WORKDIR/$CURRENT && exec bash -l'"
+if [ "x$HOST_OS" != "xWindows" ]; then
+  SSH_X=-X
+  IP=$VNC_IP
+  SSH_PORT=$CONTAINER_SSH_PORT
+else
+  WINPTY="winpty"
+  IP=$HOST
+  SSH_PORT=$HOST_SSH_PORT
+fi
+
+SSH_CMD="$WINPTY $SSH_PASS ssh $SSH_X -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -t ${UNIX_USER}@${IP} -p ${SSH_PORT} 'cd $LAB_WORKDIR/$CURRENT && exec bash -l'"
 
 if [ -z "$SSH_PASS" ]; then
   echo
-  echo "LOG: Password '$UNIX_PWD' required, please login with the following command:"
+  log_print "Password '$UNIX_PWD' required, please login with the following command:"
   echo
   echo "  $SSH_CMD"
   echo
 
-  echo "LOG: If want to login without password, there are two methods:"
+  log_print "If want to login without password, there are two methods:"
   echo
   echo "  1. Install the 'sshpass' command"
   echo
@@ -43,14 +62,15 @@ EOF
 
 fi
 
-echo
-echo "LOG: Enabling X11 Forwarding support"
-echo
+if [ "x$HOST_OS" != "xWindows" ]; then
+  echo
+  log_print "Enabling X11 Forwarding support"
+  echo
 
-which xhost >/dev/null 2>&1
-[ $? -eq 0 ] && xhost +
+  which xhost >/dev/null 2>&1
+  [ $? -eq 0 ] && xhost +
 
-cat <<EOF > ~/.ssh/ssh-x11-forward.config
+  cat <<EOF > ~/.ssh/ssh-x11-forward.config
 # X11 Forwarding Support
 Host *
    ForwardAgent yes
@@ -58,8 +78,10 @@ Host *
    ForwardX11Trusted yes
 EOF
 
+fi
+
 echo
-echo "LOG: Running '$SSH_CMD'"
+log_print "Running '$SSH_CMD'"
 echo
 
 eval "$SSH_CMD"
