tools: exit if wproxy can not run
Signed-off-by: Wu Zhangjin <wuzhangjin@gmail.com>

diff --git a/tools/docker/run b/tools/docker/run
--- a/tools/docker/run
+++ b/tools/docker/run
@@ -37,13 +37,20 @@ fi
   && echo "LOG: Resume the stopped $WPROXY_NAME" \
   && docker start `docker ps -f name=$WPROXY_NAME -f status=exited -q`
 
+# Remove old non-running wproxy
 (docker ps -f name=$WPROXY_NAME -f status=running | grep -q -v PORTS) || \
   docker rm -f $WPROXY_NAME
 
-(docker ps -f name=$WPROXY_NAME | grep -q -v PORTS) || \
+# If no running exists, start one
+(docker ps -f name=$WPROXY_NAME -f status=running | grep -q -v PORTS) || \
   (echo "LOG: Start $WPROXY_NAME" \
   && touch_token_map \
   && "$DOCKER_EXPORT_CMD" $*)
+
+# If still not running, say failure
+(docker ps -f name=$WPROXY_NAME -f status=running | grep -q -v PORTS) || \
+  (echo "ERR: Failed to start $WPROXY_NAME" >&2 \
+  && exit -1)
 
 if [ -n "$CONTAINER_NAME" ]; then
   # If already there and running, open it
